name: Go Script Practice

on: [push]

jobs:
  run-go-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # 使用するバージョン

      - name: Run script
        run: go run main.go